
server:
  port: 8080

logging.level:
  web: INFO
  root: INFO
  '[com.bptn]': DEBUG
  '[org.hibernate]': INFO
  '[org.hibernate.cfg.annotations.EntityBinder]': DEBUG
  '[org.springframework.beans.factory.support.DefaultListableBeanFactory]': DEBUG
    
spring:
  banner:
    charset: UTF-8
    location: classpath:/banner/bptn.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/feed_application 
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 